[build-system]
requires = ["setuptools",]
build-backend = "setuptools.build_meta"

[project]
name = "freebus"
version = "0.0.0"
dependencies = [
]

[project.scripts]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    ]
pythonpath = "src"
